[build]
target-dir = "/tmp"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-Awarnings",
  "-C", "target-cpu=native",
  "-C", "link-arg=-fuse-ld=lld",
  #"-C", "profile-generate=/tmp/pgo",
  #llvm-profdata merge -o /tmp/pgo/merged.profdata /tmp/pgo
  "-C", "profile-use=/tmp/pgo/merged.profdata",
]

[profile.optimized]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"

