[package]
name = "rust_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.1"

[features]
default = ["use_sort_and_hash"]
heap_funky = []
use_my_heap = []
use_bin_heap = []
use_sort_and_hash = []
use_double_sort = []

