Import('env')
env = env.Clone()

env['CPPPATH'] = [ env.include, "#%s/%s" % (env.tst_dir, env.include) ]
sources = Glob("*.cpp") + Glob("busybeaver/*.cpp")
objects = env.Object( sources )
Return('objects')

