[package]
name = "spelling_bee"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"
regex = "1.11"
rustc-hash = "2.1"

# https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles
[profile.release]
debug = true
opt-level = 3
overflow-checks = false

