MAX_SIZE=11
CUBE_ARR_LEN=MAX_SIZE + (-MAX_SIZE)%4 # we align to 64bits
COORD_LEN=4
DIMS=3
POSSIBLE_ROTATIONS=2*DIMS*4
IDX_MAX=(2**COORD_LEN) ** DIMS
COORD_MASK=IDX_MAX - 1
MAX_COORD=2**COORD_LEN - 1
MASK_Z=MAX_COORD << (2*COORD_LEN)
MASK_Y=MAX_COORD << COORD_LEN
MASK_X=MAX_COORD


